import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const origin = 'https://carta.example.com';
const image = `${origin}/og-image.jpg`;
const imageAlt = 'Carta: Your city, on paper. A framed street map of Zaragoza with PDF and SVG downloads.';
const creator = { '@type': 'Person', name: 'Diego Romero', url: 'https://example.com/' };
const pages = [
  {
    file: 'index.html', path: '/', title: 'Carta · Create City Map Prints | Diego Romero',
    description: 'Create a city map print with OpenStreetMap data. Style streets, rivers, railways and forests, choose a frame, and export PDF, SVG or PNG for free.',
    schema: { '@type': 'WebApplication', name: 'Carta', applicationCategory: 'DesignApplication', operatingSystem: 'Any', browserRequirements: 'Requires JavaScript and a modern web browser.', isAccessibleForFree: true, featureList: ['City search', 'Independent map layer styles', 'Low-resolution PDF and SVG previews (1024 px)', 'PNG export for social sharing', 'Optional PDF crop marks'] },
  },
  {
    file: 'privacy.html', path: '/privacy', title: 'Privacy & Data · Carta | Diego Romero',
    description: 'Learn how Carta handles city searches, map data, browser storage and exports, which providers it uses, and how to contact Diego Romero about your privacy.',
    schema: { '@type': 'WebPage', name: 'Privacy & data · Carta', isPartOf: { '@id': `${origin}/#website` } },
  },
];
const escape = text => text.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const hashes = [];
for (const page of pages) {
  const url = origin + page.path;
  const schema = JSON.stringify({ '@context': 'https://schema.org', '@graph': [
    { ...page.schema, '@id': `${url}#${page.path === '/' ? 'app' : 'page'}`, url, description: page.description, inLanguage: 'en', image, author: creator },
    { '@type': 'WebSite', '@id': `${origin}/#website`, name: 'Carta', url: `${origin}/`, inLanguage: 'en', publisher: creator },
  ] });
  hashes.push(`sha256-${createHash('sha256').update(schema).digest('base64')}`);
  const tags = [
    `<title>${escape(page.title)}</title>`,
    `<link rel="canonical" href="${url}">`,
    '<link rel="icon" href="/favicon.svg" type="image/svg+xml">',
    ...Object.entries({ description: page.description, author: 'Diego Romero', robots: 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1', 'application-name': 'Carta', 'theme-color': '#f5f4ec', 'twitter:card': 'summary_large_image', 'twitter:title': page.title, 'twitter:description': page.description, 'twitter:image': image, 'twitter:image:alt': imageAlt }).map(([name, content]) => `<meta name="${name}" content="${escape(content)}">`),
    ...Object.entries({ 'og:type': 'website', 'og:site_name': 'Carta', 'og:locale': 'en_US', 'og:url': url, 'og:title': page.title, 'og:description': page.description, 'og:image': image, 'og:image:secure_url': image, 'og:image:type': 'image/jpeg', 'og:image:width': '1200', 'og:image:height': '630', 'og:image:alt': imageAlt }).map(([property, content]) => `<meta property="${property}" content="${escape(content)}">`),
    `<script type="application/ld+json">${schema}</script>`,
  ];
  const path = new URL(`../public/${page.file}`, import.meta.url);
  let html = await readFile(path, 'utf8');
  html = html.replace(/\s*<!-- SEO:start -->[\s\S]*?<!-- SEO:end -->/g, '').replace(/\s*<title>[^<]*<\/title>/g, '').replace(/\s*<link rel="icon"[^>]*>/g, '');
  html = html.replace('<head>', `<head>\n    <!-- SEO:start -->\n    ${tags.join('\n    ')}\n    <!-- SEO:end -->`);
  // Keep the encoding declaration within the first 1024 bytes.
  html = html.replace(/\s*<meta charset="utf-8">/, '').replace('<head>', '<head>\n    <meta charset="utf-8">');
  await writeFile(path, html);
}
await writeFile(new URL('../worker/seo-csp.ts', import.meta.url), `// Generated by scripts/seo.mjs. Only these JSON-LD scripts may run inline.\nexport const seoScriptHashes = ${JSON.stringify(hashes)} as const;\n`);
await writeFile(new URL('../public/robots.txt', import.meta.url), `User-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile(new URL('../public/sitemap.xml', import.meta.url), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p => `  <url><loc>${origin}${p.path}</loc></url>`).join('\n')}\n</urlset>\n`);
