// Generated by scripts/seo.mjs. Only these JSON-LD scripts may run inline.
export const seoScriptHashes = ["sha256-EX+cUqw1u4hrUuNMbgP1I8j6x+xXeaznh73eYuiRIR0=","sha256-Y/cgbVRs/LJikGyNZWVfsvZ1qdkRWrGB7TG3HzV9HkE="] as const;
